### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by cjfields** [bioperl/dist-zilla-pluginbundle-bioperl#3]
A few dependencies appear to be missing and should be added, or at least they aren't being pulled into the dependency chain:
- Dist::Zilla::Plugin::Test::Compile
- Dist::Zilla::Plugin::MojibakeTests
- Dist::Zilla::Plugin::AutoMetaResources
- Dist::Zilla::Plugin::Authority
- Dist::Zilla::Plugin::EOLTests
- Dist::Zilla::Plugin::PodWeaver
- Dist::Zilla::Plugin::Git::Check
- Pod::Weaver::Section::GenerateSection
- Pod::Weaver::Section::Legal::Complicated
- Pod::Weaver::Section::Contributors
- Pod::Weaver::Plugin::Encoding
- Pod::Elemental::Transformer::List

The following are deprecated and need to be switched out:
- Dist::Zilla::Plugin::NoTabsTests, in favor of Dist::Zilla::Plugin::Test::NoTabs

**Comment by carandraug** [comment]
A new release was made and this should be fixed now.
