### ISSUE TITLE
CPAN's 02packages.details.txt.gz does not list latest Dist::Zilla::PluginBundle::BioPerl

### ISSUE THREAD

**Issue by eserte** [bioperl/dist-zilla-pluginbundle-bioperl#5]
In 02packages.details.txt.gz I see

```
Dist::Zilla::PluginBundle::BioPerl 0.20  C/CD/CDRAUG/Dist-Zilla-PluginBundle-BioPerl-0.20.tar.gz
```

but 0.23 is the latest. Maybe a PAUSE permission problem which was fixed, but there was no new release since then?

**Comment by carandraug** [comment]
This is still not fixed.  I just tried to install the latest version from CPAN and ended up with 0.20.

**Comment by carandraug** [comment]
Not sure when this happened but I went to take a look at this and it is already fixed.

**Comment by cjfields** [comment]
Wasn't working a few months back, so maybe @rbuels took care of it?

**Comment by carandraug** [comment]
Last week it was still installing the old version. It may have been fixed yesterday when I made a new release of it.
